### ISSUE TITLE
הוספת פורם עם מספר טלפון ושם של מי שמחפשים

### ISSUE THREAD

**Issue by RealByter** [RealByter/callforhelp#1]
במקום שאנשים ישתמשו באינסטגרם למשל בצורה מבולגנת למציאת אנשים שלא יוצרים קשר, יהיה לנו עמוד בו יהיה אפשר להוסיף שם של האיש שנאבד ומספר טלפון להתקשר אליו אם מוצאים אותו. ועם זה עמוד נוסף שבו אפשר לחפש שמות של אנשים. אז במשימה הזאת ספציפית עובדים על הפורם

**Comment by eladi22** [comment]
אני עובד על זה כרגע
