### ISSUE TITLE
באג: ציר הזמן של ההודעות לא פועל נכון לפעמים

### ISSUE THREAD

**Issue by RealByter** [RealByter/callforhelp#100]
מהקבוצה: "ציר הזמן לא פועל נכון (הודעות שלי מופיעות יותר למעלה, למרות שנשלחו אחרי שלך). יותר מזה אין לי מידע אז צריך לעשות בדיקות בעצמך

**Comment by RealByter** [comment]
לא הצלחתי לשחזר אז החזרתי את זה לעיבוד

**Comment by matan-gk** [comment]
When you can't reproduce you either ask for more info or you close it. Do you need more info or do you think it's not real?

**Comment by RealByter** [comment]
@matan-gk I asked for more info and got none. Tried it myself again and everything was working as it should so I closed it
