### ISSUE TITLE
באג: אלמנטים ויזואלים נחתכים עקב שורת החיפוש והמקלדת שמופיעות בטלפון

### ISSUE THREAD

**Issue by RealByter** [RealByter/callforhelp#103]
הפתרון לזה הוא להשתמש ב-dvh במקום vh לכל דבר שלוקח את כל גובה המסך (בעזרת 100vh) ולהוסיף לזה transition ל-height כדי שזה לא ייראה laggy

**Comment by matan-gk** [comment]
please include more context. Which page, which part is hidden. A screenshot would be best. Assume someone else will need to understand it and write it.

**Comment by roniash101** [comment]
includes:
- fixing the scrolling of the chat when a new message is sent (scrolls the whole page down, problomatic due to dvh)
