### ISSUE TITLE
באג: הצ'אט לא גולל למטה כאשר הודעה נוספת נשלחה

### ISSUE THREAD

**Issue by RealByter** [RealByter/callforhelp#104]
יחד עם זאת צריך לדאוג שאם משתמש בכוונה גולל בצ'אט שזה לא יכריח אותו לחזור למטה. כלומר רק כאשר הוא גולל חזרה למטה אז להפעיל את הפונקציונליות הזאת שוב

**Comment by roniash101** [comment]
.

**Comment by meytalbs** [comment]
לוקחת

**Comment by roniash101** [comment]
כדאי שבמקרה והמשתמש גולל למעלה ונשלחות הודעות חדשות שתהיה לו התראה ויזואלית על כך (כמו בווטסאפ למשל)
