### ISSUE TITLE
ציוות תומך לנתמך והפוך

### ISSUE THREAD

**Issue by RealByter** [RealByter/callforhelp#21]
נגיד שנתמך מחפש תומך אבל זה אותו הדבר לשני הצדדים רק שלתומך במקום להיכנס לצ'אט עם הנתמך, צ'אט מתווסף לרשימה שלו.
מתחילים את התהליך ברגע שנתמך מחפש תומך וזה הולך כך:
1. השגת כל הצ'אטים בהם אין נתמכים לפי סדר ה-createdAt. אם יש כאלה:
2a. הצטרפות לצ'אט הראשון (אמור להיות החדר שמחכה הכי הרבה זמן לנתמך) על ידי הצבת ה-id של הנתמך בתור ה-id של הנתמך שמחפש תומך
3a. שליחת הודעה ב-SocketIO שמודיע לתומך ולשרת שאתה מצטרף לצ'אט (room ב-SocketIO) על ידי ה-id של הצ'אט
4a. העברת הנתמך לעמוד באתר של הצ'אט עם התומך
אם אין צ'אטים שמחכים:
2b. יצירת צ'אט בפיירסטור בלי id של תומך
3b. התחברות ל-room ב-SocketIO לפי ה-id של הצ'אט שנוצר
4b. האזנה להודעה מהשרת SocketIO שמודיעה שהצטוות תומך
5b. ברגע שתומך הצטוות, מעבר לעמוד באתר של הצ'אט עם התומך

תלוי ב-#10

**Comment by ArielRotem1** [comment]
מצרף פה קובץ דוקס של הלוגיקה של הצ'אט שמתואם בין מי שעובד על הפרונטנד לבין מי שעובד על הבאקנד: [socket.io - chat logic](https://docs.google.com/document/d/1j5PYiw393nlaPW1ZuWL21EVzME8S2EK-8nG-kxMepvA/edit)
