### ISSUE TITLE
מימוש שני הפורמים של ההתחברות

### ISSUE THREAD

**Issue by RealByter** [RealByter/callforhelp#3]
כולל input validation בעזרת react-hook-form שהשם יהיה מינימום שני אותיות, שהאימייל יהיה כתובת אמיתית ושלסיסמה יהיו לפחות 8 אותיות, אות קטנה אחת, אות גדולה אחת, מספר אחד וסימן מיוחד אחד. בנוסף תהיה את האפשרות להראות ולהסתיר את הסיסמא

regex for valid email:
`/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$`
regex for valid password:
`/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}$/`

כולל יצירת המשתמש/כניסת המשתמש בעזרת פיירבייס

Relies on: #2

**Comment by Nitz-alt** [comment]
אני חושב שיש טעות בregex של המייל.
השתמשתי בזה בנתיים:
/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/
לקחתי מכאן [https://www.w3resource.com/javascript/form/email-validation.php#:~:text=To%20get%20a%20valid%20email,%5D%2B)*%24%2F.](url)
