### ISSUE TITLE
הוספת הפונטים לפרונט

### ISSUE THREAD

**Issue by RealByter** [RealByter/callforhelp#41]
צריך לב שיש יותר מפונט אחד (ראיתי 2, יכול להיות שיהיה יותר) אז להוסיף את שניהם בין אם זה באמצעות cdn או הורדה והוספה שלהם לפרויקט. ושהפונט Assistant יהיה הדיפולטיבי

**Comment by YaelEdri** [comment]
בעקרון יצא לי לעבוד על זה קצת - יש בראנץ שנקרא 
feature/set-up-font-faces
וכבר הוספתי בו את Assistant כי ביקשו ממני
לא ראיתי שיש עוד פונט באתר אז אם באמת רוצים שני פונטים אפשר פשוט להוסיף לאותו בראנץ (הוא כבר עבר פול רקווסט בעקרון)

**Comment by gertzMan** [comment]
היי, תודה. האמת שעשיתי גם שינויים למבנה של הסטייל שאני חושב שיהיה ממש נוח. רוצה לראות שניה או עסוקה?
