### ISSUE TITLE
בדיקות של הצאט

### ISSUE THREAD

**Issue by YaelEdri** [RealByter/callforhelp#63]
המקרים שצריך לבדוק:
1. מה קורה בהתחברות / התנתקות מהאינטרנט
2. מה קורה אם השרת נופל בשלב כלשהו
3. לבדוק את הקלט ששולחים בסוקט (zod)
4. לבדוק שאין HTML Injection (יש ספריה שעושה את זה)
5.

**Comment by RealByter** [comment]
@matan-gk צריך להוריד/להתעלם מ-2 ו-3 כי הם קשורים לשרת סוקטים שכבר אין לנו

**Comment by RealByter** [comment]
@matan-gk לא ברור לי פה מה המשימה. אם אכן יש בעיה כשמתנתקים מהאינטרנט, מה עושים לגבי זה? או כאשר משתמש מנסה לעשות HTML Injection, איך מגיבים אליו?

**Comment by matan-gk** [comment]
split into several topics. Closing.
