### ISSUE TITLE
תיקון באגים בצ'אט #1

### ISSUE THREAD

**Issue by RealByter** [RealByter/callforhelp#68]
מדובר פה על המסמך אקסל ששיתפו בקבוצה   [כאן](https://docs.google.com/spreadsheets/d/12pyRveXt5cY-9D6BHzluf-SG0xVcGcXpRYTrO-pObNg/edit#gid=0)

- [ ] 8
- [x] 12
- [ ] 15 - יכול להיות שנפתר כבר בגלל המעבר לנטו פיירבייס אז צריך לברר
- [x] בצד תומך, הוא יראה רק את כפתור "סיים שיחה" כמו שעודכן בפיגמה וצריך לגרום לו גם לעבוד
- [x] הורדת כפתור החסימה
- [x] צריך לשנות את האינפוט של שליחת ההודעה ככך שיכיל את המצבים השונים שלו לפי העיצוב
- [ ] כרגע בצד של הנתמך, כאשר לוחצים על "החלף תומך" הוא מראה לשנייה את החלק האדום של 'שיחה הסתיימה, ואז כאילו כבר נכנסנו לצאט חדש וזה קצת מוזר מבחינת חווית משתמש. אם אפשר לחלק על השלב בו הוא את החלק האדום של השיחה הסתיימה עדיף. אם לא, נשאיר ככה בינתיים
- [x] ניתן ללחוץ על הכפתור של "החלף תומך" גם אם עדיין אין לו תומך
- [x] הכפתור של סגירת צאט (האיקס) לא כמו העיצוב של הפיגמה. הוא צריך להיות מימין הכותרת
- [ ] עד שהוגעה באמת נשלחת צריך שההודעה עדיין תהיה באינפוט אבל שקיפות ושלא יהיה ניתן לרשום הודעה חדשה כשזה קורה. זה בעייתי טיפה בגלל ה-optimistic updates של firebase אז פחות קריטי

**Comment by YaelEdri** [comment]
אצלי בעיה 8 לא קרתה אבל עדיין כדי לדוק בעוד מכשירים
