### ISSUE TITLE
הצגת מידע נוסף בעמוד הצ'אטים של המשתמש

### ISSUE THREAD

**Issue by roniash101** [RealByter/callforhelp#82]
עבור כל צ'אט יש להציג את מספר ההודעות שלא נקראו, ואת הזמן שבו נשלחה התגובה האחרונה על פי העיצוב הנתון.

מבחינת מימוש-
על מנת לזהות הודעות שעדיין לא נקראו יש להוסיף מצב לסטטוס של ההודעה:
'sent', 'received', 'loading', 'read'

כאשר הודעה מסומנת בתור read כאשר המשתמש המקבל היה מחובר לצ'אט בזמן השליחה או שהוא נכנס לצ'אט במועד מאוחר יותר מזמן השליחה.

בנוסף, יש לפרמט את הזמן שמוצג עבור ההודעה האחרונה שנשלחה:
אם ההודעה נשלחה היום- יש להציג את השעה בה היא נשלחה
אם ההודעה נשלחה אתמול- יש לכתוב "אתמול"
אחרת- יש להציג את התאריך שבו היא נשלחה

**Comment by roniash101** [comment]
branch: feature/#82-get-chats-from-firestore

**Comment by RealByter** [comment]
reviewing
