### ISSUE TITLE
מילים ארוכות יוצאות מהקופסא, צריך text-wrapping שחותך מילים אם צריך

### ISSUE THREAD

**Issue by matan-gk** [RealByter/callforhelp#87]

**Comment by matan-gk** [comment]
@RealByter can you clarify where this happens and under which circumstances?

**Comment by RealByter** [comment]
@matan-gk when someone sends a longgggg word it goes out of the message box. So we need some sort of wrapping to prevent that

**Comment by roniash101** [comment]
.
